# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
